image: node:lts

stages:
  - dependencies
  - apps

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /init/
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'

install:
  stage: dependencies
  script:
    - yarn
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
      - node_modules
  except:
    - master
